on: workflow_dispatch

name: Deploy to EC2

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          ls
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ vars.AWS_REGION }}

      - name: push Docker image to ecr
        run: |
          docker build -t 533267220020.dkr.ecr.us-east-1.amazonaws.com/next_demo .
          docker tag next_demo:latest 533267220020.dkr.ecr.us-east-1.amazonaws.com/next_demo:latest
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          docker push 533267220020.dkr.ecr.us-east-1.amazonaws.com/next_demo:latest
 

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/next_demo:latest
          
